### ISSUE TITLE
500 Error while trying to print

### ISSUE THREAD

**Issue by MikoLone** [schemen/monsterforge#3]
Set everything up and click the print button. Used all the defaults in the form. 

https://forge.dndbox.com/minis/bestiary/571/print/

csrfmiddlewaretoken: 3u3iKziBvz5avqHt9Lx9t6btTEH87YviB2sPtEyW7BmzLLkjwn2AAbSfb8jZr67y
csrfmiddlewaretoken: 3u3iKziBvz5avqHt9Lx9t6btTEH87YviB2sPtEyW7BmzLLkjwn2AAbSfb8jZr67y
paper_format: a4
grid_size: 24
base_shape: square
force_name: no_force
darken: 0

**Comment by Sealguy2** [comment]
Same

**Comment by schemen** [comment]
Heyo!

This usually happens when an image is not really reachable by the forge. I can see that your frostgiant is trouble some, so I'd suggest you download that image and upload it to imgur.com.

The direct link to the image should then work fine!

I need to improve error handling in those cases with better feedback!

**Comment by schemen** [comment]
In the last few patches this has been greatly improved. If it occurs again, please open a new issue :)
